export const SITE_CONFIG = {
  name: "Comsri Corporation",
  shortName: "Comsri Corporation",
  description: "Premium refurbished laptops, desktops, workstations, and corporate IT hardware online in India. Fully tested 40+ points quality certified with 1-year warranty.",
  url: process.env.NEXT_PUBLIC_SITE_URL || "https://comsri.com",
  ogImage: "/images/og-default.jpg",
  logo: "/images/logo.png",
  telephone: "+91 8601-899-899",
  email: "info@comsri.com",
  address: {
    streetAddress: "Office No.-T-15 Pinnacle Business Park, MC Rd, Shanti Nagar, Andheri East",
    addressLocality: "Mumbai",
    addressRegion: "Maharashtra",
    postalCode: "400093",
    addressCountry: "IN",
  },
  social: {
    facebook: "https://www.facebook.com/comsri.store",
    instagram: "https://www.instagram.com/comsricorporation/",
    youtube: "https://www.youtube.com/@ComsriCorporation",
    twitter: "https://twitter.com/comsricorp",
  },
  defaultCategory: "Refurbished IT Hardware",
  defaultCurrency: "INR",
};
